"""empty message

Revision ID: f3a70c05fcc4
Revises: 
Create Date: 2020-11-01 19:44:10.404212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a70c05fcc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('hometown', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_firstname'), 'artist', ['firstname'], unique=False)
    op.create_index(op.f('ix_artist_hometown'), 'artist', ['hometown'], unique=False)
    op.create_index(op.f('ix_artist_lastname'), 'artist', ['lastname'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_description'), 'venue', ['description'], unique=True)
    op.create_index(op.f('ix_venue_name'), 'venue', ['name'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('time', sa.String(length=1000), nullable=True),
    sa.Column('venueId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venueId'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_description'), 'event', ['description'], unique=True)
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=True)
    op.create_table('artist_to_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistId', sa.Integer(), nullable=True),
    sa.Column('eventId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artistId'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['eventId'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_to_event')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_description'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_venue_name'), table_name='venue')
    op.drop_index(op.f('ix_venue_description'), table_name='venue')
    op.drop_table('venue')
    op.drop_index(op.f('ix_artist_lastname'), table_name='artist')
    op.drop_index(op.f('ix_artist_hometown'), table_name='artist')
    op.drop_index(op.f('ix_artist_firstname'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
